import type {
  ActivityEvent,
  Advertiser,
  Building,
  Campaign,
  Creative,
  DailyPlaylist,
  DashboardSummary,
  Screen,
} from "@/lib/types";

export const buildings: Building[] = [
  {
    id: "bld-001",
    name: "Atrium Residence",
    city: "Lisbon",
    country: "Portugal",
    type: "Residential",
    estimatedDailyAudience: 980,
    screens: 4,
    status: "Active",
  },
  {
    id: "bld-002",
    name: "Parque Central Offices",
    city: "Porto",
    country: "Portugal",
    type: "Commercial",
    estimatedDailyAudience: 1840,
    screens: 6,
    status: "Active",
  },
  {
    id: "bld-003",
    name: "Costa View Suites",
    city: "Faro",
    country: "Portugal",
    type: "Hospitality",
    estimatedDailyAudience: 620,
    screens: 2,
    status: "Inactive",
  },
  {
    id: "bld-004",
    name: "Riverside Hub",
    city: "Madrid",
    country: "Spain",
    type: "MixedUse",
    estimatedDailyAudience: 2330,
    screens: 8,
    status: "Active",
  },
];

export const screens: Screen[] = [
  {
    id: "scr-001",
    name: "Lift A North",
    buildingId: "bld-001",
    buildingName: "Atrium Residence",
    resolution: "1080x1920",
    orientation: "Portrait",
    status: "Active",
    lastSeen: "2026-05-24 09:14",
    currentPlaylist: "2026-05-24-v3",
  },
  {
    id: "scr-002",
    name: "Lift B South",
    buildingId: "bld-002",
    buildingName: "Parque Central Offices",
    resolution: "1080x1920",
    orientation: "Portrait",
    status: "Maintenance",
    lastSeen: "2026-05-24 07:41",
    currentPlaylist: "2026-05-24-v2",
  },
  {
    id: "scr-003",
    name: "Lobby Display 01",
    buildingId: "bld-004",
    buildingName: "Riverside Hub",
    resolution: "1920x1080",
    orientation: "Landscape",
    status: "Offline",
    lastSeen: "2026-05-23 22:08",
    currentPlaylist: "2026-05-24-v1",
  },
  {
    id: "scr-004",
    name: "Lift C East",
    buildingId: "bld-004",
    buildingName: "Riverside Hub",
    resolution: "1080x1920",
    orientation: "Portrait",
    status: "Inactive",
    lastSeen: "2026-05-22 16:17",
    currentPlaylist: "2026-05-23-v4",
  },
];

export const advertisers: Advertiser[] = [
  {
    id: "adv-001",
    name: "Atlas Fitness",
    contact: "Marta Silva",
    email: "marta@atlasfit.pt",
    status: "Active",
    campaigns: 2,
  },
  {
    id: "adv-002",
    name: "Nova Grocer",
    contact: "Daniel Costa",
    email: "daniel@novagrocer.com",
    status: "Active",
    campaigns: 3,
  },
  {
    id: "adv-003",
    name: "Lumen Realty",
    contact: "Sarah Moore",
    email: "s.moore@lumenrealty.es",
    status: "Inactive",
    campaigns: 1,
  },
];

export const creatives: Creative[] = [
  {
    id: "crt-001",
    name: "Summer Membership Loop",
    advertiserId: "adv-001",
    advertiserName: "Atlas Fitness",
    mediaType: "Video",
    durationSeconds: 15,
    approvalStatus: "Approved",
  },
  {
    id: "crt-002",
    name: "Fresh Market Reminder",
    advertiserId: "adv-002",
    advertiserName: "Nova Grocer",
    mediaType: "Image",
    durationSeconds: 10,
    approvalStatus: "PendingReview",
  },
  {
    id: "crt-003",
    name: "Premium Residences Tour",
    advertiserId: "adv-003",
    advertiserName: "Lumen Realty",
    mediaType: "HTML5",
    durationSeconds: 12,
    approvalStatus: "Draft",
  },
  {
    id: "crt-004",
    name: "Weekend Recovery Class",
    advertiserId: "adv-001",
    advertiserName: "Atlas Fitness",
    mediaType: "Video",
    durationSeconds: 20,
    approvalStatus: "Rejected",
  },
];

export const campaigns: Campaign[] = [
  {
    id: "cmp-001",
    name: "Atlas Morning Awareness",
    advertiserId: "adv-001",
    advertiserName: "Atlas Fitness",
    status: "Active",
    startDate: "2026-05-10",
    endDate: "2026-06-10",
    dailyBudget: 180,
    creatives: 3,
    deliveryConstraints: "Morning commute, residential buildings",
  },
  {
    id: "cmp-002",
    name: "Nova Lunch Push",
    advertiserId: "adv-002",
    advertiserName: "Nova Grocer",
    status: "Scheduled",
    startDate: "2026-05-28",
    endDate: "2026-06-30",
    dailyBudget: 220,
    creatives: 2,
    deliveryConstraints: "Office towers, weekday lunch window",
  },
  {
    id: "cmp-003",
    name: "Lumen Investor Showcase",
    advertiserId: "adv-003",
    advertiserName: "Lumen Realty",
    status: "Paused",
    startDate: "2026-05-01",
    endDate: "2026-05-31",
    dailyBudget: 260,
    creatives: 1,
    deliveryConstraints: "Mixed-use premium buildings",
  },
];

export const dailyPlaylists: DailyPlaylist[] = [
  {
    id: "pl-001",
    date: "2026-05-24",
    screenId: "scr-001",
    screenName: "Lift A North",
    buildingName: "Atrium Residence",
    version: "v3",
    status: "Downloaded",
    items: [
      { id: "pli-001", creativeName: "Summer Membership Loop", campaignName: "Atlas Morning Awareness", mediaType: "Video", position: 1, durationSeconds: 15 },
      { id: "pli-002", creativeName: "Fresh Market Reminder", campaignName: "Nova Lunch Push", mediaType: "Image", position: 2, durationSeconds: 10 },
    ],
    generatedAt: "2026-05-23 23:40",
    publishedAt: "2026-05-23 23:55",
    downloadedAt: "2026-05-24 05:18",
  },
  {
    id: "pl-002",
    date: "2026-05-24",
    screenId: "scr-002",
    screenName: "Lift B South",
    buildingName: "Parque Central Offices",
    version: "v2",
    status: "Published",
    items: [
      { id: "pli-003", creativeName: "Fresh Market Reminder", campaignName: "Nova Lunch Push", mediaType: "Image", position: 1, durationSeconds: 10 },
      { id: "pli-004", creativeName: "Summer Membership Loop", campaignName: "Atlas Morning Awareness", mediaType: "Video", position: 2, durationSeconds: 15 },
    ],
    generatedAt: "2026-05-23 23:42",
    publishedAt: "2026-05-23 23:57",
    downloadedAt: null,
  },
  {
    id: "pl-003",
    date: "2026-05-24",
    screenId: "scr-003",
    screenName: "Lobby Display 01",
    buildingName: "Riverside Hub",
    version: "v1",
    status: "Draft",
    items: [
      { id: "pli-005", creativeName: "Premium Residences Tour", campaignName: "Lumen Investor Showcase", mediaType: "HTML5", position: 1, durationSeconds: 12 },
    ],
    generatedAt: "2026-05-23 23:45",
    publishedAt: null,
    downloadedAt: null,
  },
  {
    id: "pl-004",
    date: "2026-05-23",
    screenId: "scr-004",
    screenName: "Lift C East",
    buildingName: "Riverside Hub",
    version: "v4",
    status: "Expired",
    items: [
      { id: "pli-006", creativeName: "Summer Membership Loop", campaignName: "Atlas Morning Awareness", mediaType: "Video", position: 1, durationSeconds: 15 },
      { id: "pli-007", creativeName: "Premium Residences Tour", campaignName: "Lumen Investor Showcase", mediaType: "HTML5", position: 2, durationSeconds: 12 },
    ],
    generatedAt: "2026-05-22 23:30",
    publishedAt: "2026-05-22 23:48",
    downloadedAt: "2026-05-23 05:06",
  },
];

export const dashboardSummary: DashboardSummary = {
  buildings: 24,
  screens: 86,
  activeScreens: 74,
  advertisers: 18,
  activeCampaigns: 9,
  playlistsGeneratedToday: 81,
  playlistsPendingDownload: 7,
  playsReportedToday: 128742,
};

export const recentActivity: ActivityEvent[] = [
  {
    id: "evt-001",
    type: "playlist",
    title: "Playlist generated for Lift A North",
    detail: "Version v3 published for Atrium Residence.",
    time: "09:18",
  },
  {
    id: "evt-002",
    type: "creative",
    title: "Creative approved",
    detail: "Summer Membership Loop cleared review.",
    time: "08:46",
  },
  {
    id: "evt-003",
    type: "campaign",
    title: "Campaign created",
    detail: "Nova Lunch Push scheduled for office inventory.",
    time: "07:55",
  },
  {
    id: "evt-004",
    type: "screen",
    title: "Screen downloaded playlist",
    detail: "Lift B South requested the latest daily package.",
    time: "06:11",
  },
];
